version: '3.7'

services:
  api:
    container_name: api
    image: lasting/api
    build:
      context: .
      dockerfile: Dockerfile.debug
      target: debug
    # environment:
    #   - ASPNETCORE_ENVIRONMENT=Development
    #   - ASPNETCORE_URLS=http://+:5000
    #   - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - .:/work/
      - /work/API/bin
      - /work/API/obj
      - /work/Application/bin
      - /work/Application/obj
      - /work/Domain/bin
      - /work/Domain/obj
      - /work/Persistence/bin
      - /work/Persistence/obj
      - /work/Infrastructure/bin
      - /work/Infrastructure/obj
    ports:
      - 5000:5000
    # command: bash -c "dotnet restore & dotnet watch run --no-launch-profile"
    depends_on: 
      - db
    links:
      - db
    # secrets:
    #   - cloudinaryName
  app:
    container_name: app
    image: lasting/client
    build: 
      context: client-app
      dockerfile: Dockerfile.dev
    volumes:
      - ./client-app:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3000:3000
    depends_on: 
      - api
  db:
    container_name: db
    user: root
    # networks: 
    #   - myappnetwork
    image: mcr.microsoft.com/mssql/server
    environment: 
      - "SA_PASSWORD=1StrongPwd!!"
      - "ACCEPT_EULA=Y"
      # - "MSSQL_PID=Express"
    # docker volume inspect mssqlsystem / mssqluser
    volumes:
      - /var/lib/docker/volumes/mssqlsystem/_data:/var/opt/mssql
      - /var/lib/docker/volumes/mssqluser/_data:/var/opt/sqlserver
# secrets:
#   cloudinaryName: 
#     external: true
