FROM mcr.microsoft.com/dotnet/sdk:5.0

WORKDIR /app
COPY ["API/API.csproj", "API/"]
COPY . .

ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:5000
ENV DOTNET_USE_POLLING_FILE_WATCHER=1

EXPOSE 5000

WORKDIR /app/API

CMD [ "bash", "-c", "dotnet restore && dotnet watch run --no-launch-profile" ]
